name: utility
description: "All in one Just for Avishek"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  flutter_overlay_window: ^0.5.0
  sqflite: ^2.2.8+4
  path: ^1.8.3
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  file_picker: ^6.1.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  remove_alpha_ios: true
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  assets:
    - assets/images/bkgrnd.jpg
  uses-material-design: true