name: utility
description: "All in one Just for Avishek"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^12.0.1
  flutter_overlay_window: ^0.5.0
  sqflite: ^2.2.8+4
  path: ^1.8.3
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  file_picker: ^6.1.1
  nepali_utils: ^3.0.8
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.4
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  fl_chart: ^0.71.0
  flutter_svg: ^2.2.0
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  remove_alpha_ios: true
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  assets:
    - assets/images/bkgrnd.jpg
    - assets/fonts/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
  uses-material-design: true